# Generated by Django 6.0.4 on 2026-04-16 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_comments'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
            ],
        ),
    ]
