# Generated by Django 6.0.4 on 2026-04-16 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_album'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('url', models.URLField(max_length=255)),
                ('thumbnailUrl', models.URLField(max_length=255)),
                ('albumId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.album')),
            ],
        ),
    ]
