# Generated by Django 6.0.4 on 2026-04-16 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0005_todo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='postId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='apps.post'),
        ),
    ]
