# Generated by Django 6.0.4 on 2026-04-18 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0006_alter_comments_postid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='albumId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='apps.album'),
        ),
    ]
