# Generated by Django 6.0.4 on 2026-04-23 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0011_customer_product_order_orderitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('grade', models.CharField(max_length=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
