# Generated by Django 6.0.4 on 2026-04-23 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0012_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='grade',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=1),
        ),
    ]
